export default [
  {
    title: "Software Engineer",
    company: "Awell Health",
    url: "https://www.awellhealth.com",
    location: "Remote",
    from: "April 2021",
    to: "present",
    bullets: [
      "At Awell, I work as a full-stack developer contributing to their codebase of frontend, backend and CI/CD pipelines. I work on their whole stack of web applications including Pathway Studio (for creating pathways), Care App (for orchestrating pathways) and My Care App (for pathway users i.e patients).",
      "Languages: Javascript/Typescript",
      "Tools/Frameworks: React, ArangoDB, GraphQL, MongoDB, Meteor, MoleculerJS, NextJS, Docker & Kubernetes",
    ],
  },
  {
    title: "Full-Stack Developer",
    company: "Tintash",
    url: "https://www.tintash.com",
    location: "Lahore, Pakistan",
    from: "July 2020",
    to: "April, 2021",
    bullets: [
      "[Jul-Aug] Got training sessions on Python (Django), Clean-Code and Git.",
      '[Aug-Sep] Worked on a web-based game called "Unlocked: Rogue Scientist 1990" by The Escape Game. I developed the dashboard using React/Redux and the backend in NodeJs with Sequelize.',
      "[Sep-Jan] Developed complete backend of a web-based multiplayer game using NodeJS.",
      "[Jan-Apr] Worked as a Full-Stack developer to implement complete solution of booking and automating remote experiences.",
    ],
  },
  {
    title: "Web Developer Intern (Summers)",
    company: "SolutionInn",
    url: "https://www.solutioninn.com",
    location: "Lahore, Pakistan",
    from: "June 2019",
    to: "October 2019",
    bullets: [
      "Worked on Node.JS and React.JS to create a real-time tutoring system.",
      "Worked on Socket.io to implement realtime Whiteboard, Code/Text Editor and Chat app.",
      "Implemented an efficient backend using PHP and MySQL.",
      "Worked on the main iOS app of SolutionInn, intended for students to search and buy solutions.",
    ],
  },
  {
    title: "Frontend Developer Intern (Summers)",
    company: "Respond.io",
    url: "https://respond.io/",
    location: "Lahore, Pakistan",
    from: "July 2018",
    to: "September 2018",
    bullets: [
      "Worked on Vue.JS and implemented centralized Vuex store in the web app (app.rocketbots.io)",
      "Implemented a webchat plugin for websites using PReact, Socket.io & Botman",
      "Fixed daily reported bugs on Jira.",
      "Worked on Dyson node.js server to create JSON APIs for demo bot.",
    ],
  },

  {
    title: "Top Rated Freelance Web Developer",
    company: ["Upwork", "Fiverr"],
    url: ["https://upwork.com/", "https://fiverr.com/"],
    location: "Lahore, Pakistan",
    from: "July 2016",
    to: "September 2018",
    hideInOnePage: true,
    bullets: [
      "Worked on core WordPress including theme/plugin customization & bug fixing",
      "Remained Top Rated on Upwork in 2016, completing 15+ jobs.",
      "Gained Level 1 on Fiverr.com by completing 25+ jobs.",
      "Worked on UI/UX Design & Site Optimization Tools.",
      "Also worked on graphic design (branding) projects",
    ],
  },
];
